// packages/ui/src/components/SunButton.vue
<script setup lang="ts">
import { computed } from 'vue'
import type { SunButtonProps } from '../contracts/button'
import { isDisabledState, isLabelState } from '../contracts/shared'
import '../styles/base.css'
import '../styles/button.css'

defineOptions({ inheritAttrs: false })

const props = withDefaults(defineProps<SunButtonProps>(), {
  variant: 'primary',
  size: 'md',
  nativeType: 'button',
  disabled: false,
  loading: false,
  state: 'default',
})

const emit = defineEmits<{
  click: [event: MouseEvent]
}>()

const isDisabled = computed(() => isDisabledState(props) || props.loading)
const hasLabel = computed(() => isLabelState(props))
const buttonType = computed(() => {
  return props.nativeType
})

function handleClick(event: MouseEvent) {
  if (isDisabled.value) return
  emit('click', event)
}
</script>

<template>
  <span class="sun-ui-field" :class="{ 'sun-ui-field--labeled': hasLabel }">
    <span v-if="hasLabel" class="sun-ui-label">{{ label }}</span>
    <button
      v-bind="$attrs"
      class="sun-button"
      :class="[
        `sun-button--${variant}`,
        `sun-button--${size}`,
        { 'sun-ui-disabled': isDisabled, 'is-loading': loading },
      ]"
      :type="buttonType"
      :disabled="isDisabled"
      :title="title"
      :aria-label="ariaLabel || label"
      :aria-busy="loading || undefined"
      @click="handleClick"
    >
      <slot />
    </button>
  </span>
</template>

// packages/ui/src/components/SunButton.tsx
import type { ButtonHTMLAttributes, ReactNode } from 'react'
import { cva, type VariantProps } from 'class-variance-authority'

import { cn } from '../lib/cn'
import '../styles/base.css'
import '../styles/button.css'

const buttonVariants = cva('sun-button', {
  variants: {
    variant: {
      primary: 'sun-button--primary',
      secondary: 'sun-button--secondary',
      danger: 'sun-button--danger',
      ghost: 'sun-button--ghost',
      link: 'sun-button--link',
      icon: 'sun-button--icon',
    },
    size: {
      sm: 'sun-button--sm',
      md: 'sun-button--md',
      lg: 'sun-button--lg',
      icon: 'sun-button--icon',
    },
  },
  defaultVariants: { variant: 'primary', size: 'md' },
})

export interface SunButtonProps
  extends
    ButtonHTMLAttributes<HTMLButtonElement>,
    VariantProps<typeof buttonVariants> {
  label?: string
  loading?: boolean
  children?: ReactNode
}

export function SunButton({
  variant,
  size,
  label,
  loading = false,
  disabled,
  className,
  children,
  ...props
}: SunButtonProps) {
  const isDisabled = disabled || loading
  return (
    <span className={cn('sun-ui-field', label && 'sun-ui-field--labeled')}>
      {label ? <span className="sun-ui-label">{label}</span> : null}
      <button
        className={cn(
          buttonVariants({ variant, size }),
          isDisabled && 'sun-ui-disabled',
          loading && 'is-loading',
          className
        )}
        disabled={isDisabled}
        aria-busy={loading || undefined}
        {...props}
      >
        {children}
      </button>
    </span>
  )
}
