// packages/ui/src/components/SunChatShell.vue
<script setup lang="ts">
import { computed } from 'vue'
import type { CSSProperties } from 'vue'
import type { SunChatShellProps } from '../contracts/chat-shell'
import '../styles/base.css'
import '../styles/chat-shell.css'

const props = withDefaults(defineProps<SunChatShellProps>(), {
  sidebarWidth: 280,
  sidebarCollapsed: false,
  ariaLabel: 'Chat workspace',
})

const shellStyle = computed<CSSProperties>(() => ({
  '--sun-chat-sidebar-width': `${props.sidebarWidth}px`,
}))
</script>

<template>
  <section
    data-sun-chat-shell
    class="sun-chat-shell"
    :class="{ 'sun-chat-shell--collapsed': sidebarCollapsed }"
    :style="shellStyle"
    :aria-label="ariaLabel"
  >
    <div v-if="$slots.rail" class="sun-chat-shell__rail">
      <slot name="rail" />
    </div>
    <aside v-if="!sidebarCollapsed" class="sun-chat-shell__sidebar">
      <slot name="sidebar" />
    </aside>
    <div class="sun-chat-shell__main">
      <slot />
    </div>
    <div v-if="$slots.floating" class="sun-chat-shell__floating">
      <slot name="floating" />
    </div>
  </section>
</template>

// packages/ui/src/components/SunChatShell.tsx
import type { CSSProperties, ReactNode } from 'react'

import { cn } from '../lib/cn'
import '../styles/base.css'
import '../styles/chat-shell.css'

export interface SunChatShellProps {
  sidebarWidth?: number
  sidebarCollapsed?: boolean
  ariaLabel?: string
  rail?: ReactNode
  sidebar?: ReactNode
  floating?: ReactNode
  children?: ReactNode
}

export function SunChatShell({
  sidebarWidth = 280,
  sidebarCollapsed = false,
  ariaLabel = 'Chat workspace',
  rail,
  sidebar,
  floating,
  children,
}: SunChatShellProps) {
  const style = {
    '--sun-chat-sidebar-width': `${sidebarWidth}px`,
  } as CSSProperties
  return (
    <section
      data-sun-chat-shell
      className={cn(
        'sun-chat-shell',
        sidebarCollapsed && 'sun-chat-shell--collapsed'
      )}
      style={style}
      aria-label={ariaLabel}
    >
      {rail ? <div className="sun-chat-shell__rail">{rail}</div> : null}
      {!sidebarCollapsed && sidebar ? (
        <aside className="sun-chat-shell__sidebar">{sidebar}</aside>
      ) : null}
      <div className="sun-chat-shell__main">{children}</div>
      {floating ? (
        <div className="sun-chat-shell__floating">{floating}</div>
      ) : null}
    </section>
  )
}
