// packages/ui/src/components/SunLoadingSkeleton.vue
<script setup lang="ts">
import type { SunLoadingSkeletonProps } from '../contracts/loading-skeleton'
import '../styles/base.css'
import '../styles/loading-skeleton.css'

withDefaults(defineProps<SunLoadingSkeletonProps>(), {
  lines: 3,
})
</script>

<template>
  <div class="sun-loading-skeleton" aria-hidden="true">
    <span data-sun-skeleton-line class="sun-skeleton-line sun-skeleton-line-short"></span>
    <span data-sun-skeleton-line class="sun-skeleton-line sun-skeleton-line-title"></span>
    <span
      v-for="index in lines"
      :key="index"
      data-sun-skeleton-line
      class="sun-skeleton-line"
      :class="{ 'sun-skeleton-line-muted': index === lines }"
    ></span>
  </div>
</template>

// packages/ui/src/components/SunLoadingSkeleton.tsx
import '../styles/base.css'
import '../styles/loading-skeleton.css'

export function SunLoadingSkeleton({ lines = 3 }: { lines?: number }) {
  return (
    <div className="sun-loading-skeleton" aria-hidden="true">
      {Array.from({ length: lines + 2 }, (_, index) => (
        <span
          key={index}
          data-testid="sun-skeleton-line"
          data-sun-skeleton-line
          className="sun-skeleton-line"
        />
      ))}
    </div>
  )
}
