// packages/ui/src/components/SunPagination.vue
<script setup lang="ts">
import { computed } from 'vue'
import type { SunPaginationProps } from '../contracts/pagination'
import { isDisabledState, isLabelState } from '../contracts/shared'
import '../styles/base.css'
import '../styles/pagination.css'

const props = withDefaults(defineProps<SunPaginationProps>(), {
  disabled: false,
  mobile: false,
  loading: false,
  hasMore: true,
  autoLoadOnReachEnd: false,
  state: 'default',
})

const emit = defineEmits<{
  'update:page': [page: number]
  pageChange: [page: number]
  loadMore: []
}>()

const isDisabled = computed(() => isDisabledState(props) || props.loading)
const hasLabel = computed(() => isLabelState(props))
const pageCount = computed(() => Math.max(1, Math.ceil(props.total / props.pageSize)))
const pages = computed(() => {
  return Array.from({ length: pageCount.value }, (_, index) => index + 1)
})

function changePage(page: number) {
  if (isDisabled.value || page === props.page) return
  emit('update:page', page)
  emit('pageChange', page)
}

function loadMore() {
  if (isDisabled.value || !props.hasMore) return
  emit('loadMore')
}

function handleMobileScroll(event: Event) {
  if (!props.autoLoadOnReachEnd || isDisabled.value || !props.hasMore) return
  const target = event.currentTarget as HTMLElement
  const reachedEnd = target.scrollTop + target.clientHeight >= target.scrollHeight - 4
  if (reachedEnd) {
    emit('loadMore')
  }
}
</script>

<template>
  <nav class="sun-pagination" :aria-label="ariaLabel || label || 'Pagination'">
    <div v-if="hasLabel" class="sun-ui-label">{{ label }}</div>
    <div
      v-if="mobile"
      data-sun-pagination-scroll
      class="sun-pagination__mobile-scroll"
      @scroll="handleMobileScroll"
    >
      <button
        data-sun-load-more
        class="sun-pagination__load-more"
        type="button"
        :disabled="isDisabled || !hasMore"
        :aria-busy="loading || undefined"
        @click="loadMore"
      >
        {{ hasMore ? 'Load more' : 'No more' }}
      </button>
    </div>
    <div v-else class="sun-pagination__pages">
      <button
        v-for="pageNumber in pages"
        :key="pageNumber"
        type="button"
        class="sun-pagination__page"
        :class="{ 'is-active': pageNumber === page }"
        :data-sun-page="pageNumber"
        :disabled="isDisabled"
        @click="changePage(pageNumber)"
      >
        {{ pageNumber }}
      </button>
    </div>
  </nav>
</template>

// packages/ui/src/components/SunPagination.tsx
import '../styles/base.css'
import '../styles/pagination.css'

export interface SunPaginationProps {
  page: number
  pageSize: number
  total: number
  onPageChange?: (page: number) => void
  onLoadMore?: () => void
  label?: string
  disabled?: boolean
  loading?: boolean
  mobile?: boolean
  hasMore?: boolean
}

export function SunPagination({
  page,
  pageSize,
  total,
  onPageChange,
  onLoadMore,
  label,
  disabled,
  loading,
  mobile,
  hasMore = true,
}: SunPaginationProps) {
  const pageCount = Math.max(1, Math.ceil(total / pageSize))
  const blocked = disabled || loading
  return (
    <nav className="sun-pagination" aria-label={label ?? 'Pagination'}>
      {label ? <div className="sun-ui-label">{label}</div> : null}
      {mobile ? (
        <button
          data-sun-load-more
          className="sun-pagination__load-more"
          type="button"
          disabled={blocked || !hasMore}
          onClick={onLoadMore}
        >
          {hasMore ? 'Load more' : 'No more'}
        </button>
      ) : (
        <div className="sun-pagination__pages">
          {Array.from({ length: pageCount }, (_, index) => index + 1).map(
            (pageNumber) => (
              <button
                key={pageNumber}
                type="button"
                data-sun-page={pageNumber}
                className="sun-pagination__page"
                aria-current={pageNumber === page ? 'page' : undefined}
                disabled={blocked || pageNumber === page}
                onClick={() => onPageChange?.(pageNumber)}
              >
                {pageNumber}
              </button>
            )
          )}
        </div>
      )}
    </nav>
  )
}
