// packages/ui/src/components/SunThemeProvider.vue
<script setup lang="ts">
import { computed } from 'vue'
import type { SunThemeProviderProps } from '../contracts/theme'
import { createSunThemeVars } from '../theme/createSunThemeVars'
import '../styles/base.css'
import '../styles/theme-provider.css'

const props = withDefaults(defineProps<SunThemeProviderProps>(), {
  theme: () => ({}),
})

const themeVars = computed(() => createSunThemeVars(props.theme))
</script>

<template>
  <div class="sun-theme-provider" :style="themeVars">
    <slot />
  </div>
</template>

// packages/ui/src/components/SunThemeProvider.tsx
import type { CSSProperties, ReactNode } from 'react'

import type { SunTheme } from '../contracts/theme'
import { createSunThemeVars } from '../theme/createSunThemeVars'
import '../styles/base.css'
import '../styles/theme-provider.css'

export function SunThemeProvider({
  theme = {},
  children,
}: {
  theme?: SunTheme
  children?: ReactNode
}) {
  return (
    <div
      data-testid="sun-theme-provider"
      className="sun-theme-provider"
      style={createSunThemeVars(theme) as CSSProperties}
    >
      {children}
    </div>
  )
}
