// packages/ui/src/components/SunTag.tsx
import type { CSSProperties } from 'react'

import { cn } from '../lib/cn'
import '../styles/base.css'
import '../styles/tag.css'

export interface SunTagProps {
  label: string | number
  href?: string
  color?: string
  disabled?: boolean
  className?: string
}

export function SunTag({
  label,
  href,
  color,
  disabled,
  className,
}: SunTagProps) {
  const style = color
    ? ({ backgroundColor: color } as CSSProperties)
    : undefined
  if (href && !disabled) {
    return (
      <a
        data-sun-tag
        className={cn('sun-tag', className)}
        style={style}
        href={href}
        target="_blank"
        rel="noopener noreferrer"
      >
        {label}
      </a>
    )
  }
  return (
    <span
      data-sun-tag
      className={cn('sun-tag', disabled && 'sun-ui-disabled', className)}
      style={style}
      aria-disabled={disabled || undefined}
    >
      {label}
    </span>
  )
}

// packages/ui/src/components/SunTag.vue
<script setup lang="ts">
import { computed } from 'vue'
import type { SunTagProps } from '../contracts/tag'
import { isDisabledState } from '../contracts/shared'
import '../styles/base.css'
import '../styles/tag.css'

const props = withDefaults(defineProps<SunTagProps>(), {
  disabled: false,
  state: 'default',
  color: '',
})

const isDisabled = computed(() => isDisabledState(props))
const hasLabelState = computed(() => props.state === 'label')
const tagStyle = computed(() => {
  return props.color ? { backgroundColor: props.color } : undefined
})
</script>

<template>
  <span class="sun-tag-wrap" :class="{ 'sun-ui-field--labeled': hasLabelState }">
    <span v-if="hasLabelState && label" class="sun-ui-label">{{ label }}</span>
    <span
      v-if="isDisabled || !href"
      data-sun-tag
      class="sun-tag"
      :class="{ 'sun-ui-disabled': isDisabled }"
      :style="tagStyle"
      :aria-disabled="isDisabled"
    >
      {{ label }}
    </span>
    <a
      v-else
      data-sun-tag
      class="sun-tag"
      :style="tagStyle"
      :href="href"
      target="_blank"
      rel="noopener noreferrer"
    >
      {{ label }}
    </a>
  </span>
</template>
