// apps/web/src/modules/admin/pages/AdminMetricsPage.tsx
import { Button } from '@sun-world/ui/button'
import { LoadingSkeleton } from '@sun-world/ui/loading-skeleton'
import { useAdminMetrics } from '../composables/useAdminMetrics'
import './admin.css'

export function AdminMetricsPage() {
  const data = useAdminMetrics()
  return (
    <main className="admin-page">
      <header className="admin-heading">
        <div>
          <p className="eyebrow">Operations</p>
          <h1>后台指标</h1>
          <p>请求、错误、延迟与浏览器遥测的实时快照。</p>
        </div>
        <div className="admin-actions">
          <span>
            {data.lastLoadedAt
              ? `更新于 ${data.formatDateTime(data.lastLoadedAt)}`
              : '尚未更新'}
          </span>
          <Button loading={data.loading} onClick={() => void data.refresh()}>
            刷新
          </Button>
        </div>
      </header>
      {data.errorMessage ? (
        <p className="admin-error" role="alert">
          {data.errorMessage}
        </p>
      ) : null}
      {data.loading && !data.snapshot ? (
        <LoadingSkeleton lines={6} />
      ) : (
        <>
          <MetricGrid
            cards={[
              ...data.alertCards,
              ...data.metricCards,
              ...data.telemetryCards,
              ...data.historyCards,
            ]}
          />
          <section className="admin-grid admin-grid--wide">
            <Panel title="活动告警" empty="暂无活动告警">
              {data.activeAlerts.map((alert) => (
                <div
                  className={`admin-row tone-${alert.severity}`}
                  key={alert.key}
                >
                  <strong>{alert.label}</strong>
                  <span>
                    {data.formatNumber(alert.actual)} {alert.unit} / 阈值{' '}
                    {data.formatNumber(alert.threshold)} {alert.unit}
                  </span>
                </div>
              ))}
            </Panel>
            <Panel title="状态码" empty="暂无状态码数据">
              {data.statuses.map((status) => (
                <div className="admin-row" key={status.status}>
                  <strong>{status.status}</strong>
                  <span>{data.formatNumber(status.count)} 次</span>
                </div>
              ))}
            </Panel>
          </section>
          <Panel title="路由延迟" empty="暂无路由指标">
            {data.routes.map((route) => (
              <div
                className="admin-row admin-row--route"
                key={`${route.method}:${route.route}`}
              >
                <strong>
                  {route.method} {route.route}
                </strong>
                <span>
                  {data.formatNumber(route.count)} 次 ·{' '}
                  {data.formatNumber(route.avg_duration_ms)}ms 平均 ·{' '}
                  {data.formatNumber(route.p95_duration_ms)}ms p95 ·{' '}
                  {route.error_count} 错误
                </span>
              </div>
            ))}
          </Panel>
          <section className="admin-grid admin-grid--wide">
            <Panel title="Web Vitals" empty="暂无浏览器性能数据">
              {data.webVitals.map((item) => (
                <div className="admin-row" key={item.metric}>
                  <strong>{item.metric}</strong>
                  <span>
                    {data.formatNumber(item.count)} 样本 · p95{' '}
                    {data.formatNumber(item.p95_value)} · {item.poor_count} poor
                  </span>
                </div>
              ))}
            </Panel>
            <Panel title="近期 RUM" empty="暂无遥测事件">
              {data.recentRumEvents.map((event, index) => (
                <div
                  className="admin-row"
                  key={`${event.name}:${event.timestamp}:${index}`}
                >
                  <strong>{event.name}</strong>
                  <span>
                    {event.page || '-'} · {event.severity}
                  </span>
                </div>
              ))}
            </Panel>
          </section>
        </>
      )}
    </main>
  )
}

function MetricGrid({
  cards,
}: {
  cards: ReturnType<typeof useAdminMetrics>['metricCards']
}) {
  return (
    <section className="metric-grid" aria-label="指标概览">
      {cards.map((card) => (
        <article className={`metric-card tone-${card.tone}`} key={card.key}>
          <span>{card.label}</span>
          <strong>{card.value}</strong>
          <small>{card.caption}</small>
        </article>
      ))}
    </section>
  )
}
function Panel({
  title,
  empty,
  children,
}: {
  title: string
  empty: string
  children: React.ReactNode
}) {
  const hasChildren = Array.isArray(children)
    ? children.length > 0
    : Boolean(children)
  return (
    <section className="admin-panel">
      <h2>{title}</h2>
      {hasChildren ? children : <p className="admin-empty">{empty}</p>}
    </section>
  )
}
export default AdminMetricsPage

// apps/web/src/modules/admin/pages/AdminMetricsPage.vue
<script setup lang="ts">
import { SunLoadingSkeleton as LoadingSkeleton } from '@sun-world/ui/loading-skeleton'
import { useAdminMetrics } from '../composables/useAdminMetrics'

const {
  snapshot,
  routes,
  statuses,
  webVitals,
  recentRumEvents,
  activeAlerts,
  metricCards,
  telemetryCards,
  alertCards,
  historyCards,
  loading,
  errorMessage,
  lastLoadedAt,
  refresh,
  formatDateTime,
  formatNumber,
} = useAdminMetrics()
</script>

<template>
  <main class="admin-metrics-page">
    <header class="metrics-header">
      <div class="header-copy">
        <p class="eyebrow">Operations</p>
        <h1>后台指标</h1>
        <p class="summary">
          {{ snapshot ? '请求、错误和延迟的当前进程快照' : '正在准备指标快照' }}
        </p>
      </div>

      <div class="header-actions">
        <span class="last-loaded">
          {{ lastLoadedAt ? `更新 ${formatDateTime(lastLoadedAt)}` : '尚未更新' }}
        </span>
        <button
          class="refresh-button"
          type="button"
          :disabled="loading"
          @click="refresh"
        >
          {{ loading ? '刷新中' : '刷新' }}
        </button>
      </div>
    </header>

    <section v-if="errorMessage" class="metrics-alert" role="status">
      {{ errorMessage }}
    </section>

    <section class="metrics-grid" aria-label="Alert overview">
      <LoadingSkeleton v-if="loading && !alertCards.length" :lines="3" />

      <article
        v-for="card in alertCards"
        v-else
        :key="card.key"
        class="metric-card"
        :class="`metric-card-${card.tone}`"
      >
        <p class="metric-label">{{ card.label }}</p>
        <strong class="metric-value">{{ card.value }}</strong>
        <span class="metric-caption">{{ card.caption }}</span>
      </article>
    </section>

    <section class="metrics-panel alerts-panel" aria-label="Active alerts">
      <div class="panel-heading">
        <h2>Active alerts</h2>
        <span>{{ activeAlerts.length }} rules</span>
      </div>

      <div class="alert-list">
        <div v-if="!activeAlerts.length" class="empty-state">No active alerts</div>
        <div
          v-for="alert in activeAlerts"
          :key="alert.key"
          class="alert-row"
          :class="`alert-row-${alert.severity}`"
        >
          <span class="alert-severity">{{ alert.severity }}</span>
          <div class="alert-copy">
            <strong>{{ alert.label }}</strong>
            <span>
              {{ formatNumber(alert.actual) }} {{ alert.unit }}
              / threshold {{ formatNumber(alert.threshold) }} {{ alert.unit }}
            </span>
          </div>
        </div>
      </div>
    </section>

    <section class="metrics-grid" aria-label="Metrics history overview">
      <LoadingSkeleton v-if="loading && !historyCards.length" :lines="3" />

      <article
        v-for="card in historyCards"
        v-else
        :key="card.key"
        class="metric-card"
        :class="`metric-card-${card.tone}`"
      >
        <p class="metric-label">{{ card.label }}</p>
        <strong class="metric-value">{{ card.value }}</strong>
        <span class="metric-caption">{{ card.caption }}</span>
      </article>
    </section>

    <section class="metrics-grid" aria-label="请求指标概览">
      <LoadingSkeleton v-if="loading && !snapshot" :lines="3" />

      <article
        v-for="card in metricCards"
        v-else
        :key="card.key"
        class="metric-card"
        :class="`metric-card-${card.tone}`"
      >
        <p class="metric-label">{{ card.label }}</p>
        <strong class="metric-value">{{ card.value }}</strong>
        <span class="metric-caption">{{ card.caption }}</span>
      </article>
    </section>

    <section class="metrics-grid" aria-label="RUM metrics overview">
      <LoadingSkeleton v-if="loading && !telemetryCards.length" :lines="3" />

      <article
        v-for="card in telemetryCards"
        v-else
        :key="card.key"
        class="metric-card"
        :class="`metric-card-${card.tone}`"
      >
        <p class="metric-label">{{ card.label }}</p>
        <strong class="metric-value">{{ card.value }}</strong>
        <span class="metric-caption">{{ card.caption }}</span>
      </article>
    </section>

    <section class="metrics-content">
      <article class="metrics-panel">
        <div class="panel-heading">
          <h2>路由延迟</h2>
          <span>{{ routes.length }} 条</span>
        </div>

        <div class="route-list">
          <div v-if="!routes.length" class="empty-state">暂无路由指标</div>
          <div
            v-for="route in routes"
            :key="`${route.method}:${route.route}`"
            class="route-row"
          >
            <div class="route-main">
              <span class="method">{{ route.method }}</span>
              <span class="route-path">{{ route.route }}</span>
            </div>
            <div class="route-stats">
              <span>{{ formatNumber(route.count) }} 次</span>
              <span>{{ formatNumber(route.avg_duration_ms) }}ms 平均</span>
              <span>{{ formatNumber(route.p95_duration_ms) }}ms p95</span>
              <span>{{ formatNumber(route.p99_duration_ms) }}ms p99</span>
              <span>{{ formatNumber(route.max_duration_ms) }}ms 峰值</span>
              <span
                class="route-errors"
                :class="{ active: route.error_count > 0 }"
              >
                {{ formatNumber(route.error_count) }} 错误
              </span>
            </div>
          </div>
        </div>
      </article>

      <aside class="metrics-panel status-panel">
        <div class="panel-heading">
          <h2>状态码</h2>
          <span>{{ statuses.length }} 类</span>
        </div>

        <div class="status-list">
          <div v-if="!statuses.length" class="empty-state">暂无状态码数据</div>
          <div
            v-for="item in statuses"
            :key="item.status"
            class="status-row"
          >
            <span
              class="status-code"
              :class="{
                warning: item.status >= 400 && item.status < 500,
                danger: item.status >= 500,
              }"
            >
              {{ item.status }}
            </span>
            <div class="status-bar">
              <span
                :style="{
                  width: `${Math.max(
                    8,
                    (item.count / Math.max(1, snapshot?.total_requests ?? 1)) * 100
                  )}%`,
                }"
              ></span>
            </div>
            <strong>{{ formatNumber(item.count) }}</strong>
          </div>
        </div>
      </aside>
    </section>

    <section class="metrics-content rum-content">
      <article class="metrics-panel">
        <div class="panel-heading">
          <h2>Web Vitals</h2>
          <span>{{ webVitals.length }} metrics</span>
        </div>

        <div class="route-list">
          <div v-if="!webVitals.length" class="empty-state">No RUM metrics yet</div>
          <div
            v-for="item in webVitals"
            :key="item.metric"
            class="route-row"
          >
            <div class="route-main">
              <span class="method">{{ item.metric }}</span>
              <span class="route-path">
                avg {{ formatNumber(item.avg_value) }},
                p95 {{ formatNumber(item.p95_value) }},
                p99 {{ formatNumber(item.p99_value) }},
                max {{ formatNumber(item.max_value) }}
              </span>
            </div>
            <div class="route-stats">
              <span>{{ formatNumber(item.count) }} samples</span>
              <span>{{ formatNumber(item.good_count) }} good</span>
              <span>{{ formatNumber(item.needs_improvement_count) }} needs work</span>
              <span
                class="route-errors"
                :class="{ active: item.poor_count > 0 }"
              >
                {{ formatNumber(item.poor_count) }} poor
              </span>
            </div>
          </div>
        </div>
      </article>

      <aside class="metrics-panel status-panel">
        <div class="panel-heading">
          <h2>Recent RUM</h2>
          <span>{{ recentRumEvents.length }} events</span>
        </div>

        <div class="route-list">
          <div v-if="!recentRumEvents.length" class="empty-state">No events yet</div>
          <div
            v-for="event in recentRumEvents"
            :key="`${event.name}:${event.timestamp}:${event.page}`"
            class="route-row"
          >
            <div class="route-main">
              <span class="method">{{ event.severity }}</span>
              <span class="route-path">{{ event.name }}</span>
            </div>
            <div class="route-stats">
              <span>{{ event.page || '-' }}</span>
            </div>
          </div>
        </div>
      </aside>
    </section>
  </main>
</template>

<style scoped>
.admin-metrics-page {
  min-height: 100%;
  padding: var(--space-6);
  color: var(--text-default);
  background: var(--bg-page);
  overflow: auto;
}

.metrics-header {
  display: flex;
  align-items: flex-start;
  justify-content: space-between;
  gap: var(--space-4);
  margin-bottom: var(--space-6);
}

.header-copy {
  display: grid;
  gap: var(--space-2);
}

.eyebrow {
  margin: 0;
  color: var(--color-accent);
  font-size: var(--font-size-sm);
  font-weight: 700;
  text-transform: uppercase;
}

h1,
h2,
p {
  margin: 0;
}

h1 {
  color: var(--text-strong);
  font-size: var(--font-size-3xl);
  line-height: var(--line-height-tight);
}

h2 {
  color: var(--text-strong);
  font-size: var(--font-size-xl);
  line-height: var(--line-height-tight);
}

.summary,
.last-loaded,
.metric-caption,
.panel-heading span {
  color: var(--text-secondary);
  font-size: var(--font-size-md);
}

.header-actions {
  display: flex;
  align-items: center;
  gap: var(--space-3);
}

.refresh-button {
  min-width: 84px;
  min-height: var(--btn-height-default);
  border: 1px solid var(--border-active);
  border-radius: var(--radius-md);
  padding: var(--btn-padding-default);
  color: var(--btn-text-color);
  background: var(--color-brand);
  font-size: var(--font-size-md);
  cursor: pointer;
  transition:
    transform var(--motion-duration-fast) var(--motion-ease-standard),
    opacity var(--motion-duration-fast) var(--motion-ease-standard);
}

.refresh-button:hover:not(:disabled) {
  transform: translateY(-1px);
}

.refresh-button:disabled {
  cursor: not-allowed;
  opacity: var(--btn-disabled-opacity);
}

.metrics-alert {
  margin-bottom: var(--space-4);
  border: 1px solid var(--color-danger);
  border-radius: var(--radius-md);
  padding: var(--space-3) var(--space-4);
  color: var(--color-danger);
  background: var(--bg-component);
}

.metrics-grid {
  display: grid;
  grid-template-columns: repeat(4, minmax(0, 1fr));
  gap: var(--space-4);
  margin-bottom: var(--space-6);
}

.alerts-panel {
  margin-bottom: var(--space-6);
}

.alert-list {
  display: grid;
  gap: var(--space-3);
}

.alert-row {
  display: flex;
  align-items: center;
  gap: var(--space-3);
  min-width: 0;
  border: 1px solid var(--border-lighter);
  border-radius: var(--radius-md);
  padding: var(--space-3) var(--space-4);
  background: var(--bg-raised);
}

.alert-row-critical {
  border-color: var(--color-danger);
}

.alert-row-warning {
  border-color: var(--color-warning);
}

.alert-severity {
  flex: 0 0 auto;
  min-width: 72px;
  border-radius: var(--radius-sm);
  padding: var(--space-1) var(--space-2);
  color: var(--text-strong);
  background: var(--bg-component);
  font-size: var(--font-size-sm);
  font-weight: 700;
  text-align: center;
  text-transform: uppercase;
}

.alert-copy {
  display: grid;
  gap: var(--space-1);
  min-width: 0;
  color: var(--text-secondary);
  font-size: var(--font-size-sm);
}

.alert-copy strong {
  overflow-wrap: anywhere;
  color: var(--text-strong);
  font-size: var(--font-size-md);
}

.metric-card,
.metrics-panel {
  border: 1px solid var(--border-default);
  border-radius: var(--radius-md);
  background: var(--bg-component);
}

.metric-card {
  display: grid;
  gap: var(--space-2);
  min-height: 132px;
  padding: var(--space-5);
  animation: metrics-enter var(--motion-duration-slow) var(--motion-ease-emphasized)
    both;
}

.metric-label {
  color: var(--text-secondary);
  font-size: var(--font-size-md);
}

.metric-value {
  color: var(--text-strong);
  font-size: var(--font-size-3xl);
  line-height: var(--line-height-tight);
}

.metric-card-success {
  border-color: var(--color-success);
}

.metric-card-warning {
  border-color: var(--color-warning);
}

.metric-card-danger {
  border-color: var(--color-danger);
}

.metrics-content {
  display: grid;
  grid-template-columns: minmax(0, 1fr) minmax(280px, 360px);
  gap: var(--space-4);
  align-items: start;
}

.rum-content {
  margin-top: var(--space-4);
}

.metrics-panel {
  min-width: 0;
  padding: var(--space-5);
}

.panel-heading {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: var(--space-3);
  margin-bottom: var(--space-4);
}

.route-list,
.status-list {
  display: grid;
  gap: var(--space-3);
}

.route-row,
.status-row {
  border: 1px solid var(--border-lighter);
  border-radius: var(--radius-md);
  background: var(--bg-raised);
}

.route-row {
  display: grid;
  gap: var(--space-3);
  padding: var(--space-4);
}

.route-main,
.route-stats,
.status-row {
  display: flex;
  align-items: center;
  gap: var(--space-3);
}

.route-main {
  min-width: 0;
}

.method,
.status-code {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  min-width: 56px;
  min-height: 28px;
  border-radius: var(--radius-sm);
  color: var(--color-brand);
  background: var(--bg-brand-light);
  font-size: var(--font-size-sm);
  font-weight: 700;
}

.route-path {
  min-width: 0;
  overflow-wrap: anywhere;
  color: var(--text-strong);
  font-size: var(--font-size-md);
}

.route-stats {
  flex-wrap: wrap;
  color: var(--text-secondary);
  font-size: var(--font-size-sm);
}

.route-errors.active,
.status-code.danger {
  color: var(--color-danger);
  background: var(--bg-component);
}

.status-code.warning {
  color: var(--color-warning);
  background: var(--bg-component);
}

.status-row {
  min-height: 48px;
  padding: var(--space-3);
}

.status-bar {
  flex: 1;
  height: 8px;
  border-radius: var(--radius-full);
  background: var(--bg-fill);
  overflow: hidden;
}

.status-bar span {
  display: block;
  height: 100%;
  border-radius: inherit;
  background: var(--color-accent);
}

.empty-state {
  border: 1px dashed var(--border-default);
  border-radius: var(--radius-md);
  padding: var(--space-6);
  color: var(--text-secondary);
  text-align: center;
  background: var(--bg-raised);
}

@keyframes metrics-enter {
  from {
    opacity: 0;
    transform: translateY(8px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

@media (max-width: 1024px) {
  .metrics-grid,
  .metrics-content {
    grid-template-columns: repeat(2, minmax(0, 1fr));
  }

  .metrics-panel:first-child {
    grid-column: 1 / -1;
  }
}

@media (max-width: 720px) {
  .admin-metrics-page {
    padding: var(--space-4);
  }

  .metrics-header,
  .header-actions {
    align-items: stretch;
    flex-direction: column;
  }

  .metrics-grid,
  .metrics-content {
    grid-template-columns: 1fr;
  }

  .route-stats {
    display: grid;
    grid-template-columns: repeat(2, minmax(0, 1fr));
  }
}

@media (prefers-reduced-motion: reduce) {
  .metric-card,
  .refresh-button {
    animation: none;
    transition: none;
  }
}
</style>
