// apps/web/src/modules/home/pages/HomePage.tsx
import { useEffect, useRef } from 'react'

import { BlogHomeFeed } from '@/modules/blog/ui/BlogHomeFeed'
import { SelfInfoCard } from '@/modules/blog/ui/SelfInfoCard'
import {
  buildWebsiteJsonLd,
  canonicalUrl,
  useJsonLd,
  usePageMeta,
} from '@/shared/seo'
import { IcpFilingCard } from '../ui/IcpFilingCard'
import { WeatherCard } from '../ui/WeatherCard'
import './home-react.css'

export function HomePage() {
  const sidebar = useRef<HTMLElement>(null)
  const sentinel = useRef<HTMLDivElement>(null)
  usePageMeta({
    title: 'Sun World',
    description: '记录全栈开发、AI、图形编辑器与工程实践的个人技术博客。',
    canonical: canonicalUrl('/'),
  })
  useJsonLd(buildWebsiteJsonLd(), 'website')

  useEffect(() => {
    if (!sentinel.current || !sidebar.current || !window.IntersectionObserver)
      return
    const observer = new IntersectionObserver(([entry]) => {
      if (!sidebar.current) return
      if (entry.isIntersecting) {
        const overflow = Math.max(
          sidebar.current.offsetHeight - window.innerHeight,
          -64
        )
        sidebar.current.style.top = `${-overflow}px`
      } else sidebar.current.style.removeProperty('top')
    })
    observer.observe(sentinel.current)
    return () => observer.disconnect()
  }, [])

  return (
    <div className="home-page">
      <aside className="home-sidebar" ref={sidebar} aria-label="个人信息与天气">
        <SelfInfoCard />
        <WeatherCard />
        <IcpFilingCard className="desktop-icp-card" />
        <div ref={sentinel} />
      </aside>
      <BlogHomeFeed />
      <IcpFilingCard className="mobile-icp-card" />
    </div>
  )
}

export default HomePage

// apps/web/src/modules/home/pages/HomePage.vue
<script setup lang="ts" name="content">
import { onMounted, onUnmounted, ref } from 'vue'
import SelfInfoCard from '@/modules/blog/ui/SelfInfoCard.vue'
import WeatherCard from '@/modules/home/ui/WeatherCard.vue'
import IcpFilingCard from '@/modules/home/ui/IcpFilingCard.vue'
import BlogHomeFeed from '@/modules/blog/ui/BlogHomeFeed.vue'
import {
  buildWebsiteJsonLd,
  canonicalUrl,
  useJsonLd,
  usePageMeta,
} from '@/shared/seo'

const leftRef = ref<HTMLElement | null>(null)
const bottomRef = ref<HTMLElement | null>(null)
let observer: IntersectionObserver | null = null

usePageMeta({
  title: 'Sun World',
  description:
    'Sun World 是一个记录全栈开发、AI、图形编辑器和工程实践的个人技术博客。',
  canonical: canonicalUrl('/'),
})
useJsonLd(buildWebsiteJsonLd(), 'website')

onMounted(() => {
  if (!bottomRef.value) return

  observer = new IntersectionObserver(
    ([entry]) => {
      if (entry.isIntersecting) {
        const leftHeight = leftRef.value?.offsetHeight
        if (!leftHeight) return

        const overflow = Math.max(leftHeight - window.innerHeight, -64)
        leftRef.value?.style.setProperty('top', `${-overflow}px`)
      } else {
        leftRef.value?.style.removeProperty('top')
      }
    },
    {
      root: null,
      threshold: 0,
    }
  )
  observer.observe(bottomRef.value)
})

onUnmounted(() => {
  observer?.disconnect()
})
</script>

<template>
  <div class="home-page">
    <aside class="left" ref="leftRef" aria-label="个人信息与天气">
      <SelfInfoCard />
      <WeatherCard />
      <IcpFilingCard class="desktop-icp-card" />
      <div ref="bottomRef" class="sidebar-sentinel"></div>
    </aside>

    <BlogHomeFeed />
    <IcpFilingCard class="mobile-icp-card" />
  </div>
</template>

<style scoped>
.home-page {
  width: 100%;
  max-width: var(--container-max-width);
  margin: 0 auto;
  padding: var(--space-8) var(--container-inline-padding) var(--space-12);
  background:
    linear-gradient(180deg, var(--bg-accent-soft), transparent 18rem),
    var(--bg-page);
  display: grid;
  grid-template-columns: minmax(260px, 35rem) minmax(0, 1fr);
  gap: var(--space-6);
  align-items: start;
  min-height: 100%;
}

.left {
  height: fit-content;
  position: sticky;
  top: 80px;
  padding-bottom: 50px;
  display: flex;
  flex-direction: column;
  gap: var(--space-4);
}

.sidebar-sentinel {
  height: 2px;
}

.mobile-icp-card {
  display: none;
}

@media screen and (max-width: 1024px) {
  .home-page {
    grid-template-columns: 1fr;
    padding-top: var(--space-6);
  }

  .left {
    display: none;
  }

  .mobile-icp-card {
    display: flex;
  }
}

@media screen and (max-width: 695px) {
  .home-page {
    padding: var(--space-4) var(--space-3) var(--space-10);
    gap: var(--space-3);
  }
}
</style>
